version: 2

jobs:
  build:

    environment:

      BUNDLE_RETRY: 3

    docker:
      - image: circleci/ruby:2.4.9-buster
        environment:
            BUNDLE_JOBS: 3
            BUNDLE_RETRY: 3
            BUNDLE_PATH: vendor/bundle

      - image: selenium/standalone-chrome:3.141.59

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Update Bundler
          command: |
            gem update bundler
            bundle update --bundler

      - run:
          name: Install Gems
          command: bundle check || bundle install

      - run:
          name: Env
          command: |
            gem env
            which gem
            which irb
            which ruby

      - save_cache:
          key: gems-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
         name: Test
         command: bundle exec ruby sel_test.rb

      - store_test_results:
          when: always
          path: /tmp/report.xml

      - store_artifacts:
          when: always
          path: /tmp/
